FROM dbatools/sqlinstance2
USER root

# Install PowerShell 7.4 now please
RUN apt-get update && apt install -y powershell
# install git
RUN apt install -y git

# some cleanup
RUN apt-get autoremove -y \
    && apt-get clean -y